// packages/framework-testing/astro-react/src/App.tsx
import "./App.css";
import { RuxContainer, RuxGlobalStatusBar } from "@astrouxds/react";

function App() {
  return (
    <>
      <RuxGlobalStatusBar appName="Astro" appVersion="React" />
      <main className="grid gap-4 p-4 grid-cols-1 lg:grid-cols-12">
        <RuxContainer className="lg:col-span-2">
          <header slot="header">Header</header>
        </RuxContainer>

        <RuxContainer className="lg:col-span-10">
          <header slot="header">Header</header>
        </RuxContainer>
      </main>
    </>
  );
}

export default App;

// packages/starter-kits/astro-vue/src/App.vue
<script setup lang="ts"></script>

<template>
  <rux-global-status-bar app-name="Astro"></rux-global-status-bar>
  <main class="grid gap-4 p-4 grid-cols-1 lg:grid-cols-12">
    <rux-container class="lg:col-span-2">
      <header slot="header">Header</header>
    </rux-container>
    <rux-container class="lg:col-span-10">
      <header slot="header">Header</header>
    </rux-container>
  </main>
</template>

<style scoped></style>
