// packages/starter-kits/react-starter/src/App.js
import "./App.css";
import { RuxProgress } from "@astrouxds/react";

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <div>
          <RuxProgress />
        </div>
        <p>
          Welcome to Astro UXDS web components in React! Check out the README.md
          for more information on getting started.
        </p>
        <a
          className="App-link"
          href="https://astrouxds.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          astrouxds.com
        </a>
      </header>
    </div>
  );
}

export default App;

// packages/starter-kits/angular-starter/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'angular-starter';
}

<header
  style="
    text-align: center;
    min-height: 100vh;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    font-size: calc(10px + 2vmin);
    color: white;
  "
>
  <div>
    <rux-progress></rux-progress>
  </div>
  <p>
    Welcome to Astro UXDS Web Components in Angular! <br />
    Check out the README.md for more information on getting started.
  </p>
  <a
    href="https://astrouxds.com"
    target="_blank"
    rel="noopener noreferrer"
    style="color: var(--color-background-interactive-default)"
  >
    astrouxds.com
  </a>
</header>
