// packages/web-components/src/stories/astro-sandboxes/forms/react/basic/src/index.js
import { StrictMode } from 'react'
import ReactDOM from 'react-dom'
import '@astrouxds/astro-web-components/dist/astro-web-components/astro-web-components.css'

import App from './App'

const rootElement = document.getElementById('root')
ReactDOM.render(
    <StrictMode>
        <App />
    </StrictMode>,
    rootElement
)

// packages/web-components/src/stories/astro-sandboxes/forms/vue/validation/src/main.js
import { createApp } from 'vue'
import App from './App.vue'

import '@astrouxds/astro-web-components/dist/astro-web-components/astro-web-components.css'

// import './index.css'
import { defineCustomElements } from '@astrouxds/astro-web-components/loader'
defineCustomElements()

createApp(App).mount('#app')
