// packages/web-components/src/stories/astro-sandboxes/forms/vue/validation/src/main.js
import { createApp } from 'vue'
import App from './App.vue'

import '@astrouxds/astro-web-components/dist/astro-web-components/astro-web-components.css'

// import './index.css'
import { defineCustomElements } from '@astrouxds/astro-web-components/loader'
defineCustomElements()

createApp(App).mount('#app')

// packages/framework-testing/astro-react/src/main.tsx
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.tsx";
import "./index.css";
import "@astrouxds/astro-web-components/dist/astro-web-components/astro-web-components.css";

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
