// packages/starter-kits/vue2-starter/src/App.vue
<template>
  <div id="app">
    <rux-global-status-bar appname="App">
      <rux-clock aos="1557503698781" los="2019-05-10T16:21:12.000Z"></rux-clock>
    </rux-global-status-bar>

    <div id="cont" class="container">
      <h1>Astro Vue 2 Starter-Kit</h1>
    </div>
  </div>
</template>

<script>
export default {
  name: "App",
  data() {
    return {};
  },
};
</script>

<style>
.container {
  width: 50%;
  margin: 50px auto 0 auto;
  text-align: center;
}
</style>

// packages/starter-kits/svelte-starter/App.svelte
<script></script>
<main>
  <rux-global-status-bar appname="App">
    <rux-clock aos="1557503698781" los="2019-05-10T16:21:12.000Z"></rux-clock>
    </rux-global-status-bar>
    <div>
      <h1>Astro Svelte Starter Kit</h1>
    </div>
</main>
<style>
  div{
    width: 40%;
    margin: 50px auto 0 auto;
    text-align: center;
  }
</style>
